### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by willymec** [tbar0970/jethro-pmm#536]
Installer came up and I added all the usual options and after running the install it comes up with this error.

> 

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in /home/holyspir/public_html/jethro/include/installer.class.php:110 Stack trace: #0 /home/holyspir/public_html/jethro/include/installer.class.php(110): PDO->query('CREATE TABLE pe...') #1 /home/holyspir/public_html/jethro/include/installer.class.php(33): Installer->initDB() #2 /home/holyspir/public_html/jethro/templates/installer.template.php(15): Installer->printBody() #3 /home/holyspir/public_html/jethro/include/installer.class.php(19): include('/home/holyspir/...') #4 /home/holyspir/public_html/jethro/index.php(51): Installer->run() #5 {main} thrown in /home/holyspir/public_html/jethro/include/installer.class.php on line 110

**Comment by tbar0970** [comment]
This is tricky to dig into without knowing exactly which query is triggering the error.

You could try adding this to your conf.php:
```
define('STRICT_MODE_FIX', TRUE);
```

**Comment by willymec** [comment]
From A2hosting support 

> To resolve this, you can try reducing the size of columns. For example, if the encoding that is being used is utf8, then it should be VARCHAR(255). If it is utfmb4, then - 191. Depending on the application settings, you can also try using a different character set (like UTF-8 instead of UTF8MB4), or use a different engine (like MYISAM, which allows more bytes per prefix).--

The error message "1071 Specified key was too long; max key length is 767 bytes" means that application is unable to populate its database. It tries to create a key and hits the limit on the number of bytes allowed for a database prefix. MySQL has a prefix limitation of 767 bytes in InnoDB, and 1000 bytes in MYISAM.  To resolve this, you can try reducing the size of columns. For example, if the encoding that is being used is utf8, then it should be VARCHAR(255). If it is utfmb4, then - 191. Depending on the application settings, you can also try using a different character set (like UTF-8 instead of UTF8MB4), or use a different engine (like MYISAM, which allows more bytes per prefix).

> 

The fix was in phpMyAdmin , operations, collation, changed to utf8_unicode_ci instead of UTF8MB4.
 Emptied the database and reinstalled.
