### ISSUE TITLE
mailchimp script failing

### ISSUE THREAD

**Issue by kristanslack** [tbar0970/jethro-pmm#870]
Hi,

The mail chimp script is failing with an exception:

Fatal error: Uncaught PharException: Extraction from phar "/tmp/jethro-mc-1676867940/response.tar" failed: Cannot extract ".", internal error in /home/aliceang/public_html/jethro/scripts/mailchimp_sync.php:271
Stack trace:
#0 /home/aliceang/public_html/jethro/scripts/mailchimp_sync.php(271): PharData->extractTo('/tmp/jethro-mc-...', NULL, true)
#1 /home/aliceang/public_html/jethro/scripts/mailchimp_sync.php(81): run_mc_sync(Object(DrewM\MailChimp\MailChimp), 2, '41f1a38d0e')
#2 {main}
  thrown in /home/aliceang/public_html/jethro/scripts/mailchimp_sync.php on line 271

==
It worked a few days ago. I'm unaware of having changed any mail chimp related settings either on mail chimp or in Jethro.

thanks,
Kristan

**Comment by jefft** [comment]
The relevant bit of code only runs if Mailchimp returned an error ("errored_operations" > 0):

https://github.com/tbar0970/jethro-pmm/blob/9d0f01544b56084575c8dd156e9a738d69e23c6c/scripts/mailchimp_sync.php#L260-L294

This is not a common codepath, and it's quite possible Mailchimp now returning something the script doesn't expect. 

Specifically, the script assumes the returned bytes are a `tar.gz` file containing JSON. There are people [saying](https://stackoverflow.com/questions/38843938/phardata-extractto-method-failed-to-extract-tar-gz-on-linux-environment) that it might be returning a `tar.gz` containing a `.` element.

Perhaps you could edit `scripts/mailchimp_sync.php` and just after line 266:

https://github.com/tbar0970/jethro-pmm/blob/9d0f01544b56084575c8dd156e9a738d69e23c6c/scripts/mailchimp_sync.php#L266

Copy the tar.gz somewhere for later inspection:

```copy($tgzfile, "/tmp/mailchimp.tgz");```

Then see what's in it:

```tar tvf /tmp/mailchimp.tgz```

**Comment by jefft** [comment]
Having experienced this for myself, I can confirm it happens when Mailchimp returns errors in a tar.gz file with an unnecessary `.` entry:
```
$ tar tf response.tar
.
./u4xj0hswis.json
```
See attached [response.tar.gz](https://github.com/tbar0970/jethro-pmm/files/11133601/response.tar.gz) for an example. The PHP code:
```php
<?php
$tgzfile="response.tar.gz";
$p = new PharData($tgzfile);
$p2 = $p->decompress();
$p2->extractTo("subdir", NULL, TRUE);
```
results in the error:
```
PHP Fatal error:  Uncaught PharException: Extraction from phar "/tmp/mailchimp_pharbug/response.tar.gz" failed: Cannot extract ".", internal error in /tmp/mailchimp_pharbug/extract.php:6
Stack trace:
#0 /tmp/mailchimp_pharbug/extract.php(6): PharData->extractTo()
#1 {main}
  thrown in /tmp/mailchimp_pharbug/extract.php on line 6
```
